Lecture04
skE-UsK/RaiseTech_AWS pull request #6
Opened 2023-06-17 12:35 UTC by skE-UsK

課題４を提出します。よろしくお願いします。

2023-06-17 12:54 UTC, MasatoshiMizumoto requested changes
2件コメント入れましたのでご対応ください！
https://github.com/skE-UsK/RaiseTech_AWS/pull/6/files

2023-06-17 12:54 UTC, MasatoshiMizumoto commented on .DS_Store
`.DS_Store`が沢山あるんで`.gitignore`で対応して、既にpushしたものも消してもらえますと！

2023-06-17 12:54 UTC, MasatoshiMizumoto commented on lecture04/lecture04ver0/lecture04.md
> +### EC2 から RDS へ接続し、正常であることを確認して報告してください。
ここは見出しであるべきではないです。こういう使い方は無しです！
太字の代わりに使ってますかね？太字のスタイリング方法は別にあります！
私はこれが好みです。
```suggestion
- AWS 上に新しく VPC を作ってください。
- EC2 と RDS を構築してください。
- EC2 から RDS へ接続し、正常であることを確認して報告してください。
```

2023-06-18 14:43 UTC, skE-UsK commented on .DS_Store
.gitignore を作成して.DS_Storeを対象に追加しました。（.DS_Storeを削除）

2023-06-18 14:59 UTC, skE-UsK commented on lecture04/lecture04ver0/lecture04.md
> +### EC2 から RDS へ接続し、正常であることを確認して報告してください。
lecture04/lecture04.mdが今回提出する.mdです。
同時に提出してしまったlecture04/lecture04ver0/lecture04.mdは途中まで作成したのちに詰まって、コピペ用に一応取っておいたものなので、紛らわしいため削除しました。すみません。

2023-06-18 15:49 UTC, skE-UsK commented on lecture04/lecture04ver0/lecture04.md
> +### EC2 から RDS へ接続し、正常であることを確認して報告してください。
git hubの見方が分からないため質問です。
対象(３,4,5)の行にある###見出しを-箇条書きに修正してもらえましたよということですか？

緑→対象の行
### AWS 上に新しく VPC を作ってください。
### EC2 と RDS を構築してください。
### EC2 から RDS へ接続し、正常であることを確認して報告してください。

赤→修正前
### AWS 上に新しく VPC を作ってください。
### EC2 と RDS を構築してください。
### EC2 から RDS へ接続し、正常であることを確認して報告してください。

緑→修正後(Masatoshi Mizumotoさんが修正）
- AWS 上に新しく VPC を作ってください。
- EC2 と RDS を構築してください。
- EC2 から RDS へ接続し、正常であることを確認して報告してください。

2023-06-18 16:12 UTC, skE-UsK commented on lecture04/lecture04ver0/lecture04.md
> +### EC2 から RDS へ接続し、正常であることを確認して報告してください。
太文字の代わりに使っていたわけではなく、当初は見出しだけ作成して間をうめていくつもりだったのが、長くなるにつれて目次みたいなのも欲しくなって、そのままの形で残ったのだと思います。
箇条書きの方を見たらこれが正解だと感じました。

2023-06-19 14:11 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応ください！

2023-06-19 14:11 UTC, MasatoshiMizumoto commented on lecture04/.gitignore
2つも用意しなくていいずですね。
まああってもいいです！

2023-06-19 14:11 UTC, MasatoshiMizumoto commented on .gitignore
`Files Changed`のページで確認してほしいんですが、空行がないと警告がでます！

2023-06-19 15:00 UTC, skE-UsK commented on lecture04/.gitignore
1つにまとめました。

2023-06-19 15:03 UTC, skE-UsK commented on .gitignore
空行を追加しました。

2023-06-19 15:05 UTC, skE-UsK commented on .gitignore
同時に、間違って今回不要なものまで上がってしまいました。すみません。

2023-06-19 15:14 UTC, MasatoshiMizumoto approved these changes
お疲れさまでした！
LGTM!

2023-06-19 15:20 UTC, merged